tasks:
  Yifi-Torrents:
    rss: http://yify-torrents.com/rss/0/1080p/All/0
    imdb:
      min_score: 4.5
      min_votes: 1000
      min_year: 2010
      reject_genres:
        - documentary
        - musical
        - music
        - biography
        - romance
        - drama
        - western
    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: xxxxx
      password: yyyyy

  FamilyGuy:
    rss: http://showrss.info/feeds/27.rss
    exists_series: /media/Toshiba/Downloads/Torrents/Complete
    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: xxxxx
      password: yyyyy
  
  UFC:
   rss: http://kickass.to/usearch/ufc/?rss=1
   limit_new: 5
   transmission:
     enabled: yes
     host: localhost
     port: 9091
     username: xxxxx
     password: yyyyy  

# Busqueda de Subtitulos

  subtitles_series:
    find:
      path:
        - /media/Toshiba/Video/Series/X-Men_Evolution
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    periscope:
      languages:
        - es

  subtitles_movies:
    find:
      path:
        - /media/Toshiba/Downloads/Torrents/Complete/
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    periscope:
      languages:
        - es
